# Generated by Django 4.0.6 on 2022-08-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameApp.categoria'),
        ),
        migrations.AddField(
            model_name='animal',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameApp.categoria'),
        ),
        migrations.AddField(
            model_name='comida',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameApp.categoria'),
        ),
        migrations.AddField(
            model_name='cosa',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameApp.categoria'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameApp.categoria'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='palabrasDiferentes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
