# Generated by Django 4.0.6 on 2022-08-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0002_accion_categoria_animal_categoria_comida_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accion',
            name='listaPalabras',
        ),
        migrations.RemoveField(
            model_name='accion',
            name='palabrasDiferentes',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='listaPalabras',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='palabrasDiferentes',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='listaPalabras',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='palabrasDiferentes',
        ),
        migrations.RemoveField(
            model_name='cosa',
            name='listaPalabras',
        ),
        migrations.RemoveField(
            model_name='cosa',
            name='palabrasDiferentes',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='listaPalabras',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='palabrasDiferentes',
        ),
        migrations.AddField(
            model_name='accion',
            name='nombre',
            field=models.CharField(default='nombreAccion', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='nombre',
            field=models.CharField(default='nombreAnimal', max_length=50),
        ),
        migrations.AddField(
            model_name='comida',
            name='nombre',
            field=models.CharField(default='nombreComida', max_length=50),
        ),
        migrations.AddField(
            model_name='cosa',
            name='nombre',
            field=models.CharField(default='nombreCosa', max_length=50),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(default='nombrePelicula', max_length=50),
        ),
    ]
