# Generated by Django 4.0.6 on 2022-08-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0003_remove_accion_listapalabras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='cosa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='listaPalabras',
            field=models.TextField(default='asd', max_length=50),
        ),
        migrations.DeleteModel(
            name='Accion',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
        migrations.DeleteModel(
            name='Cosa',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
